# Generated by Django 2.0.1 on 2018-01-30 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('Kg', 'Kilogram'), ('g', 'Gram'), ('Lbs', 'Pounds'), ('Packet', 'Packet')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=250, verbose_name='Recipe Title')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('photo', models.ImageField(blank=True, upload_to='upload/recipe_photos', verbose_name='photo')),
                ('info', models.TextField(default='', help_text='Short description of the recipe', verbose_name='info')),
                ('servings', models.IntegerField(default=0, help_text='enter total number of servings', verbose_name='servings')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
    ]
