# Generated by Django 2.0.1 on 2018-02-06 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('Kg', 'Kilogram'), ('g', 'Gram'), ('Lbs', 'Pounds'), ('Packet', 'Packet')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=250, verbose_name='Recipe Title')),
                ('photo', models.ImageField(blank=True, upload_to='upload/recipe_photos', verbose_name='photo')),
                ('info', models.TextField(help_text='enter information about the recipe', verbose_name='info')),
                ('cook_time', models.IntegerField(default=None, help_text='enter time in minutes', verbose_name='cook time')),
                ('servings', models.IntegerField(help_text='enter total number of servings', verbose_name='servings')),
                ('directions', models.TextField(default=None, verbose_name='directions')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
    ]
