# Generated by Django 2.0.1 on 2018-02-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='info',
            field=models.TextField(help_text='enter information about the recipe', max_length=250, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/upload/recipe_photos', verbose_name='photo'),
        ),
    ]
