# Generated by Django 2.0.1 on 2018-01-31 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(default=None, help_text='enter time in minutes', verbose_name='cook time'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default=None, verbose_name='directions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='info',
            field=models.TextField(help_text='enter information about the recipe', verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(help_text='enter total number of servings', verbose_name='servings'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
    ]
