# Generated by Django 2.0.1 on 2018-01-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20180131_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='ingredientcost',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.DeleteModel(
            name='IngredientCost',
        ),
    ]
