# Generated by Django 2.0.1 on 2018-02-01 08:14

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('recipe', '0005_auto_20180131_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', taggit.managers.TaggableManager(blank=True, help_text='separate with commas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Course')),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', taggit.managers.TaggableManager(blank=True, help_text='separate with commas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='cuisine')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe')),
            ],
        ),
    ]
