# Generated by Django 2.0.1 on 2018-02-01 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20180201_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipe.Course'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipe.Cuisine'),
        ),
    ]
