# Generated by Django 2.0.1 on 2018-01-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20180129_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kilogram'), ('g', 'Gram'), ('Lbs', 'Pounds'), ('Packet', 'Packet')], max_length=200),
        ),
    ]
